### ISSUE TITLE
cover image does not appear on twitter link

### ISSUE THREAD

**Issue by cderv** [yihui/rmarkdown-cookbook#274]
I am not sure why but the cover image does not appear correctly in a tweet
![image](https://user-images.githubusercontent.com/6791940/90538030-48b26080-e17e-11ea-9424-d83ddc254c0f.png)

it does for other. 
![image](https://user-images.githubusercontent.com/6791940/90538106-6253a800-e17e-11ea-915c-0e01463a235d.png)

Cover image is set for twitter
https://github.com/yihui/rmarkdown-cookbook/blob/8d5a559dc05273c28b50cbb625538a5b3da06098/index.html#L22
so there must be something else 🤔

**Comment by yihui** [comment]
Should be fixed now. Thanks!

**Comment by cderv** [comment]
It still does not work NOW but there may be a cache thing so I'll try later. The fix should work.

**Comment by yihui** [comment]
Yes, it may take a while. I just checked some tweets and at least this one works for me now: https://twitter.com/chrisderv/status/1288593402460884992
